const fs = require("fs"), path = require("path");
const DATA = path.join(__dirname, "../data/sample-opportunities.json");
const d = JSON.parse(fs.readFileSync(DATA, "utf8"));
const today = new Date().toISOString().split("T")[0];
const existing = new Set(d.map(o => o.id));

const ops = [
  {id:"top01",organisation_name:"Chartered Institute of Marketing",role:"CIM Marketing Challenge",courses:["marketing","business","economics"],description:"Enter the CIM Marketing Challenge — producing a real marketing strategy for a live client brief, judged by industry professionals.",why_it_helps:"CIM recognition is the gold standard for Marketing applications.",skills:["Marketing strategy","Consumer insight","Campaign planning"],mode:"online",region:"UK",weekly_commitment:"Project-based",min_age:16,town:"Anywhere",apply_url:"https://www.cim.co.uk/qualifications/",achievements:["Team reached CIM Marketing Challenge national final"],reflection_prompts:["What consumer insight most changed your marketing strategy?"],example_sentence:"Competing in the CIM Marketing Challenge showed me that good marketing is always about understanding people, not just products.",is_active:true,last_checked:today,type:"competition"},
  {id:"top02",organisation_name:"Charity Digital",role:"Digital Marketing Volunteer",courses:["marketing","business","data-science-ai","computer-science"],description:"Help a small charity develop and execute their digital marketing strategy — content creation, social media management and campaign analytics.",why_it_helps:"Real digital marketing responsibility with measurable outcomes is the most applicable evidence for Marketing applications.",skills:["Content marketing","Social media analytics","Campaign planning"],mode:"online",region:"UK",weekly_commitment:"3 hrs/week",min_age:16,town:"Anywhere",apply_url:"https://charitydigital.org.uk/",achievements:["Grew a charity Instagram following by 35% over 3 months"],reflection_prompts:["What metric told you more about audience engagement than follower count alone?"],example_sentence:"Managing a charity's social media showed me that good marketing is about building trust, not accumulating reach.",is_active:true,last_checked:today,type:"volunteering"},
  {id:"top03",organisation_name:"CISI",role:"Student Investor Challenge",courses:["finance","economics","mathematics","data-science-ai"],description:"Compete in the CISI Student Investor Challenge — managing a virtual portfolio and presenting investment rationale to industry judges.",why_it_helps:"CISI is directly cited by Finance and Economics tutors as evidence of applied quantitative thinking.",skills:["Portfolio management","Equity analysis","Financial modelling"],mode:"online",region:"UK",weekly_commitment:"Competition period",min_age:16,town:"Anywhere",apply_url:"https://www.cisi.org/",achievements:["Portfolio ranked in top 15% nationally"],reflection_prompts:["What market event forced you to revise a position you had been confident in?"],example_sentence:"Competing in the CISI challenge taught me that financial analysis is about managing uncertainty, not eliminating it.",is_active:true,last_checked:today,type:"competition"},
  {id:"top04",organisation_name:"Bank of England",role:"School Leaver Insight Programme",courses:["finance","economics","mathematics"],description:"Apply for the Bank of England School Leaver Insight programme — gaining exposure to monetary policy, financial stability and data economics.",why_it_helps:"Bank of England exposure is exceptional evidence for Finance and Economics applications.",skills:["Monetary policy understanding","Economic modelling","Financial analysis"],mode:"in-person",region:"UK",weekly_commitment:"Programme week",min_age:17,town:"London",apply_url:"https://www.bankofengland.co.uk/careers",achievements:["Completed Bank of England school insight programme"],reflection_prompts:["What did learning about monetary policy reveal about the relationship between economics and politics?"],example_sentence:"Attending the Bank of England insight day showed me that monetary policy is as much about communication as mathematics.",is_active:true,last_checked:today,type:"volunteering"},
  {id:"top05",organisation_name:"Institution of Civil Engineers",role:"ICE Bridges to Schools Competition",courses:["civil-engineering","engineering","mathematics"],description:"Participate in the ICE Bridges to Schools programme — building a model bridge and competing against other schools judged by civil engineers.",why_it_helps:"ICE programme participation is directly cited by civil engineering departments as evidence of practical problem-solving.",skills:["Structural design","Load calculations","Engineering teamwork"],mode:"in-person",region:"UK",weekly_commitment:"Competition-based",min_age:14,town:"Anywhere",apply_url:"https://www.ice.org.uk/destinations/schools-and-colleges",achievements:["Team bridge won best design award"],reflection_prompts:["What engineering failure during testing taught you more than the successful result would have?"],example_sentence:"Competing in the ICE bridge challenge showed me that structural engineering is learned through failure, not success.",is_active:true,last_checked:today,type:"competition"},
  {id:"top06",organisation_name:"Institution of Civil Engineers",role:"ICE Community Volunteer",courses:["civil-engineering","engineering","geography"],description:"Volunteer with ICE in your local community — helping with infrastructure outreach events and supporting ICE education days.",why_it_helps:"ICE volunteer involvement builds the professional network and awareness that civil engineering applications need.",skills:["Infrastructure awareness","Community engagement","Professional mentoring"],mode:"in-person",region:"UK",weekly_commitment:"Event-based",min_age:17,town:"Anywhere",apply_url:"https://www.ice.org.uk/destinations/schools-and-colleges",achievements:["Volunteered at 3 ICE regional events"],reflection_prompts:["What did working with practising civil engineers reveal about the gap between university and professional practice?"],example_sentence:"Volunteering at ICE events showed me that civil engineering is shaped as much by constraints on the ground as calculations on paper.",is_active:true,last_checked:today,type:"volunteering"},
  {id:"top07",organisation_name:"National Youth Theatre",role:"NYT REP Company Member",courses:["theatre-performance","english-literature"],description:"Audition for NYT REP — the National Youth Theatre rep company, performing in professional London venues and touring nationally.",why_it_helps:"NYT REP is the most competitive youth theatre programme in the UK and is universally recognised by drama school admissions.",skills:["Professional performance","Ensemble acting","Physical theatre"],mode:"in-person",region:"UK",weekly_commitment:"Intensive rehearsal periods",min_age:16,town:"London",apply_url:"https://www.nyt.org.uk/take-part",achievements:["Cast in an NYT REP production at a major London venue"],reflection_prompts:["What did rehearsing at a professional level reveal about your instincts as a performer?"],example_sentence:"Performing with NYT REP showed me that professional theatre is built on discipline, not inspiration.",is_active:true,last_checked:today,type:"volunteering"},
  {id:"top08",organisation_name:"Chickenshed Theatre",role:"Inclusive Theatre Volunteer",courses:["theatre-performance","education","social-work"],description:"Support Chickenshed's inclusive theatre-making — assisting with rehearsals, community workshops and performances.",why_it_helps:"Inclusive theatre practice at Chickenshed is distinctive evidence for Theatre and Education applications alike.",skills:["Inclusive facilitation","Ensemble devising","Adaptive communication"],mode:"in-person",region:"UK",weekly_commitment:"2-3 hrs/week",min_age:16,town:"London",apply_url:"https://www.chickenshed.org.uk/get-involved/",achievements:["Supported an inclusive community production with 40 performers"],reflection_prompts:["How did making theatre with people of different abilities change your understanding of what performance is for?"],example_sentence:"Working at Chickenshed showed me that theatre is most powerful when it includes people who are normally excluded from it.",is_active:true,last_checked:today,type:"volunteering"},
  {id:"top09",organisation_name:"British Sociological Association",role:"BSA Student Essay Prize",courses:["sociology","politics","social-work"],description:"Enter the BSA undergraduate essay prize — writing an original sociological analysis of a social issue.",why_it_helps:"BSA essay recognition demonstrates independent sociological thinking that tutors want to see before degree study.",skills:["Sociological analysis","Academic writing","Theoretical application"],mode:"online",region:"UK",weekly_commitment:"Project-based",min_age:17,town:"Anywhere",apply_url:"https://www.britsoc.co.uk/opportunities/",achievements:["Shortlisted for BSA student essay award"],reflection_prompts:["Which sociological theory best explained the phenomenon you studied, and which fell short?"],example_sentence:"Writing a competition essay on precarious employment taught me that sociology is not about describing society but explaining it.",is_active:true,last_checked:today,type:"competition"},
  {id:"top10",organisation_name:"Nuffield Foundation",role:"Social Science Research Volunteer",courses:["sociology","economics","psychology","politics"],description:"Support Nuffield-funded researchers on projects examining education, welfare and social change in the UK.",why_it_helps:"Research involvement at a major social science funder is exceptional evidence for Sociology and PPE applications.",skills:["Literature review","Survey design","Social analysis"],mode:"hybrid",region:"UK",weekly_commitment:"3 hrs/week",min_age:18,town:"London",apply_url:"https://www.nuffieldfoundation.org/about/work-with-us",achievements:["Contributed to a literature review on intergenerational mobility"],reflection_prompts:["What finding most challenged your prior understanding of social mobility?"],example_sentence:"Assisting social science research at Nuffield showed me how carefully constructed evidence actually changes policy.",is_active:true,last_checked:today,type:"volunteering"},
  {id:"top11",organisation_name:"Royal Geographical Society",role:"GeoMentor Volunteer",courses:["geography","environmental-science","politics"],description:"Work with the RGS GeoMentors programme to bring geographical thinking into schools — supporting field trips and sustainability projects.",why_it_helps:"Working with the UK's leading geography body is strong evidence of subject commitment for Geography applications.",skills:["Geographical fieldwork","Spatial analysis","Environmental communication"],mode:"in-person",region:"UK",weekly_commitment:"2 hrs/fortnight",min_age:17,town:"London",apply_url:"https://www.rgs.org/schools/geomentors/",achievements:["Supported a school fieldwork project on urban microclimate change"],reflection_prompts:["What geographical pattern in the field data surprised you most?"],example_sentence:"Supporting a school fieldwork project showed me that geography is always about the tension between what maps show and what places actually are.",is_active:true,last_checked:today,type:"volunteering"},
  {id:"top12",organisation_name:"Ordnance Survey",role:"GetOutside Champion",courses:["geography","environmental-science","data-science-ai"],description:"Become an OS GetOutside Champion — promoting outdoor exploration, map-reading and geographical awareness in your community.",why_it_helps:"Engagement with the UK's national mapping agency demonstrates genuine geographical enthusiasm and public engagement skills.",skills:["Cartography awareness","Community engagement","Outdoor navigation"],mode:"in-person",region:"UK",weekly_commitment:"2 hrs/fortnight",min_age:16,town:"Anywhere",apply_url:"https://getoutside.ordnancesurvey.co.uk/champions/",achievements:["Led three community map-reading walks"],reflection_prompts:["What does a map leave out, and why does that matter geographically?"],example_sentence:"Leading community map walks taught me that geographical literacy is about reading landscape as much as reading lines.",is_active:true,last_checked:today,type:"volunteering"},
  {id:"top13",organisation_name:"Action Against Hunger",role:"Fundraising Volunteer",courses:["geography","international-relations","social-work"],description:"Organise and run fundraising events for Action Against Hunger — raising money and awareness for global food security programmes.",why_it_helps:"Fundraising for a global food security charity combines geographical awareness with applied organisational skills.",skills:["Fundraising event management","Global food systems awareness","Campaign communication"],mode:"hybrid",region:"UK",weekly_commitment:"3 hrs/week",min_age:16,town:"Anywhere",apply_url:"https://www.actionagainsthunger.org.uk/get-involved/",achievements:["Organised a fundraising event raising £900"],reflection_prompts:["What did learning about food insecurity reveal about the geography of global inequality?"],example_sentence:"Fundraising for Action Against Hunger showed me that food security is a geographical and political problem, not just a logistical one.",is_active:true,last_checked:today,type:"volunteering"},
  {id:"top14",organisation_name:"Crimestoppers",role:"Community Safety Volunteer",courses:["criminology","law","social-work","psychology"],description:"Support Crimestoppers community safety campaigns — running public awareness events, school visits and crime prevention talks.",why_it_helps:"Community crime prevention engagement demonstrates the social understanding that criminology applications require.",skills:["Community safety communication","Crime prevention awareness","Public speaking"],mode:"in-person",region:"UK",weekly_commitment:"2 hrs/week",min_age:17,town:"Anywhere",apply_url:"https://crimestoppers-uk.org/keeping-communities-safe/",achievements:["Delivered crime prevention talks in 4 schools"],reflection_prompts:["What did community engagement reveal about how people actually understand crime and safety?"],example_sentence:"Running community safety events with Crimestoppers showed me that crime prevention is built on trust between communities and institutions.",is_active:true,last_checked:today,type:"volunteering"},
  {id:"top15",organisation_name:"Howard League for Penal Reform",role:"Student Member & Campaigner",courses:["criminology","law","sociology","politics"],description:"Join the Howard League as a student member — attending events, contributing to campaigns and engaging with penal reform policy.",why_it_helps:"Howard League engagement demonstrates serious, evidence-based engagement with the criminal justice system that criminology courses require.",skills:["Criminal justice policy analysis","Penal reform advocacy","Academic engagement"],mode:"hybrid",region:"UK",weekly_commitment:"2 hrs/week",min_age:17,town:"London",apply_url:"https://howardleague.org/get-involved/",achievements:["Contributed to a Howard League campaign on youth custody"],reflection_prompts:["What does the evidence on reoffending rates reveal about the purpose of punishment?"],example_sentence:"Working with the Howard League showed me that criminology is meaningless unless it engages with the people inside the system.",is_active:true,last_checked:today,type:"volunteering"},
];

const added = ops.filter(o => !existing.has(o.id));
added.forEach(o => d.push(o));
fs.writeFileSync(DATA, JSON.stringify(d, null, 2));

const counts = {};
d.forEach(o => o.courses.forEach(c => counts[c] = (counts[c]||0)+1));
const thin = Object.entries(counts).filter(([,v]) => v < 5).sort((a,b) => a[1]-b[1]);
console.log("Total:", d.length, "| Added:", added.length);
console.log(thin.length ? "Still under 5: " + thin.map(([k,v]) => v+" "+k).join(", ") : "All courses 5+ ✓");
